

class KMP(object):

    R = 256                                             # the radix

    def __init__(self, pat, text):
        self.pat = pat
        self.text = text
        M = len(self.pat)

        self.dfa = [[None]*M for i in range(KMP.R)]     # The KMP automoton
        self.dfa[ord(self.pat[0])][0] = 1


    ###########################################################################
    ########################### Client of the class: ##########################

def test_KMP():
    text = "GAATTGCTAGCAATTGCTAGCAATTGCTAGCAATTCAACCAGATCACCGAAAACTGTCCTCCAAAT\
        CCCTCACACTCCCAAATTCGCGGGCTTCTGCCTCTTAGACCACTCTACCCTATTCCCCACACTCACCGGA\
        CCAAAGCCGCGGCCCTTCCGTTTCTTTGCTTTTGAAAGACCCCACCCGTAGGTGGCAAGCTAGCTTAAGT\
        ACGCCACTTTGCAAGGCATGGAAAAATACATAACTGAGAATAGGAAAGTTCAGATCAAGGTCAGGAACAA\
        GAAACAGCTGAATACCAAACAGGATATCTGTGGTAAGCGGTTCCTGCCCCGGCTCAGGGCCAAGAACAGA\
        GAGACAGCTGAGTGATGGGCCAAACAGGATATCTGTGGTAAGCAGTTCCTGCCCCGGCTCGGGGCCAAGA\
        CAGATGGTCCCCAGATGCGGTCCAGCCCTCAGCAGTTTCTAGTGAATCATCAGATGTTTCCAGGGTGCCC\
        AAGGACCTGAAAATGACCCTGTACCTTATTTGAACTAACCAATCAGTTCGCTTCTCGCTTCTGTTCGCGC\
        CTTCCGCTCTCCGAGCTCAATAAAAGAGCCCACAACCCCTCACTCGGCGCGCCAGTCTTCCGATAGACTG\
        GTCGCCCGGGTACCCGTATTCCCAATAAAGCCTCTTGCTGTTTGCATCCGAATCGTGGTCTCGCTGTTCC\
        TGGGAGGGTCTCCTCTGAGTGATTGACTACCCACGACGGGGGTCTTTCATTTGGGGGCTCGTCCGGGATT\
        GGAGACCCCTGCCCAGGGACCACCGACCCACCACCGGGAGGTAAGCTGGCCAGCAACTTATCTGTGTCTG\
        CCGATTGTCTAGTGTCTATGTTTGATGTTATGCGCCTGCGTCTGTACTAGTTAGCTAACTAGCTCTGTAT\
        TGGCGGACCCGTGGTGGAACTGACGAGTTCTGAACACCCGGCCGCAACCCTGGGAGACGTCCCAGGGACT\
        TGGGGGCCGTTTTTGTGGCCCGACCTGAGGAAGGGAGTCGATGTGGAATCCGACCCCGTCAGGATATGTG\
        TTCTGGTAGGAGACGAGAACCTAAAACAGTTCCCGCCTCCGTCTGAATTTTTGCTTTCGGTTTGGAACCG\
        AGCCGCGCGTCTTGTCTGCTGCAGCATCGTTCTGTGTTGTCTCTGTCTGACTGTGTTTCTGTATTTGTCT\
        AAAATTAGGGCCAGACTGTTACCACTCCCTTAAGTTTGACCTTAGGTCACTGGAAAGATGTCGAGCGGAT\
        GCTCACAACCAGTCGGTAGATGTCAAGAAGAGACGTTGGGTTACCTTCTGCTCTGCAGAATGGCCAACCT"

    words = ["GAATT", "CAATTGCTA", "CCTCAC", "AGTTTGAC", "AACCT", "CAACCT"]
    for i in range(len(words)): 
        # print(substring_search_brute_force(words[i], text) == \
        #       substring_search_brute_force_X(words[i], text))
        print(substring_search_brute_force(words[i], text))
        print(substring_search_brute_force_X(words[i], text))

def main():
    text = "GAATTGCTAGCAATTGCTAGCAATTGCTAGCAATTCAACCAGATCACCGAAAACTGTCCTCCAAAT"
    pat = "AATTCAA"
    kmp = KMP(pat, text)
    print(kmp.dfa)


if __name__ == '__main__':